create sequence owner_sequence start with 1 increment by 1;
create table owner_data (dob date, id integer not null, departament varchar(255), email varchar(255), name varchar(255) not null, primary key (name));
create sequence owner_sequence start with 1 increment by 1;
create table owner_data (dob date, id integer not null, departament varchar(255), email varchar(255), name varchar(255) not null, primary key (name));
create sequence owner_sequence start with 1 increment by 1;
create table owner_data (dob date, id integer not null, departament varchar(255), email varchar(255), name varchar(255) not null, primary key (name));
create sequence owner_sequence start with 1 increment by 1;
create table owner_data (dob date, id integer not null, departament varchar(255), email varchar(255), name varchar(255) not null, primary key (name));
create sequence owner_sequence start with 1 increment by 1;
create table owner_data (dob date, id integer not null, departament varchar(255), email varchar(255), name varchar(255) not null, primary key (name));
